# Generated by Django 3.0.5 on 2020-08-23 00:10

import apps.control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Profile_file),
        ),
    ]
