# Generated by Django 3.0.5 on 2020-08-26 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_comment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='assigned',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 26, 20, 38, 2, 184461, tzinfo=utc), verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 26, 20, 38, 9, 511912, tzinfo=utc), verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment_file',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='comment_file',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 26, 20, 38, 23, 625036, tzinfo=utc), verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kamban',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='kamban',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='members',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date_change_t',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Change'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_create_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Create'),
            preserve_default=False,
        ),
    ]
