# Generated by Django 3.0.5 on 2020-08-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20200826_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='assigned',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='comment_file',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='comment_file',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='kamban',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='kamban',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='members',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='members',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='date_create_t',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_change_t',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_create_t',
        ),
    ]
