# Generated by Django 3.0.5 on 2020-08-28 21:26

import apps.control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20200826_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/img/perfil.png', null=True, upload_to=apps.control.models.Profile_file),
        ),
    ]
